services:
  backend:
    image: ghcr.io/m1kx/max-cube-backend:latest
    environment:
      - CUBE_IP_ADDRESS=192.168.0.153
      - APIKEY=testtoken
    volumes:
      - ./database.db:/app/database.db
  frontend:
    image: ghcr.io/m1kx/max-cube-frontend:latest
    ports:
      - "3023:3000"